"""beacon-kb: Agentic retrieval-augmented generation library.

This package provides a modular, plugin-driven pipeline for building
knowledge bases and retrieval-augmented generation systems.

All sub-module imports are eager and side-effect free: no network,
filesystem, logging-handler, or credential operations are performed
when this module is imported.
"""

from __future__ import annotations

__author__ = "Rohit Kumar"

# ---------------------------------------------------------------------------
# Public re-exports from sub-modules
# Eager imports: these sub-modules are pure Python with no side effects,
# so eager loading is safe and imposes no startup cost.
# ---------------------------------------------------------------------------

from beacon_kb.config import (
    AgenticConfig,
    AnswerConfig,
    BeaconConfig,
    CoreConfig,
    PluginsConfig,
    RetrievalConfig,
)
from beacon_kb.errors import (
    AgenticError,
    BackendError,
    BeaconError,
    BudgetError,
    CitationError,
    ConfigError,
    IngestionError,
    PluginConflict,
    PluginError,
    PluginNotFound,
    ProtocolMismatch,
    ReadinessError,
)
from beacon_kb.facade import KnowledgeBase
from beacon_kb.models import (
    AgenticStep,
    AgenticTrace,
    AnswerResponse,
    BuildRunId,
    Chunk,
    ChunkId,
    ChunkKind,
    Citation,
    Corpus,
    CorpusId,
    Evidence,
    EvidenceId,
    EvidenceRole,
    Fingerprint,
    Hit,
    IngestionChange,
    Query,
    QueryId,
    RawDocument,
    Revision,
    RevisionId,
    Section,
    SectionId,
    Source,
    SourceId,
    SyncReport,
    SyncStatus,
    TraceId,
    make_build_run_id,
    make_chunk_id,
    make_evidence_id,
    make_revision_id,
    make_section_id,
    make_source_id,
)
from beacon_kb.protocols import (
    Chunker,
    Connector,
    CorpusRouter,
    DenseRetriever,
    Embedder,
    EvidenceGrader,
    Fusion,
    Generator,
    Parser,
    ProgressObserver,
    QueryPlanner,
    Reranker,
    SessionStore,
    SparseRetriever,
    StopCondition,
    Store,
    TokenCounter,
    Tool,
)
from beacon_kb.version import PLUGIN_API_VERSION, __version__

__all__ = [
    "PLUGIN_API_VERSION",
    "AgenticConfig",
    "AgenticError",
    "AgenticStep",
    "AgenticTrace",
    "AnswerConfig",
    "AnswerResponse",
    "BackendError",
    "BeaconConfig",
    "BeaconError",
    "BudgetError",
    "BuildRunId",
    "Chunk",
    "ChunkId",
    "ChunkKind",
    "Chunker",
    "Citation",
    "CitationError",
    "ConfigError",
    "Connector",
    "CoreConfig",
    "Corpus",
    "CorpusId",
    "CorpusRouter",
    "DenseRetriever",
    "Embedder",
    "Evidence",
    "EvidenceGrader",
    "EvidenceId",
    "EvidenceRole",
    "Fingerprint",
    "Fusion",
    "Generator",
    "Hit",
    "IngestionChange",
    "IngestionError",
    "KnowledgeBase",
    "Parser",
    "PluginConflict",
    "PluginError",
    "PluginNotFound",
    "PluginsConfig",
    "ProgressObserver",
    "ProtocolMismatch",
    "Query",
    "QueryId",
    "QueryPlanner",
    "RawDocument",
    "ReadinessError",
    "Reranker",
    "RetrievalConfig",
    "Revision",
    "RevisionId",
    "Section",
    "SectionId",
    "SessionStore",
    "Source",
    "SourceId",
    "SparseRetriever",
    "StopCondition",
    "Store",
    "SyncReport",
    "SyncStatus",
    "TokenCounter",
    "Tool",
    "TraceId",
    "__author__",
    "__version__",
    "make_build_run_id",
    "make_chunk_id",
    "make_evidence_id",
    "make_revision_id",
    "make_section_id",
    "make_source_id",
]
